# lazygit config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: always
    pager: delta --paging=never

gui:
  switchTabsWithPanelJumpKeys: true

refresher:
  fetchInterval: 120
